sudo: false
language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: "prathameshtajane-github"

script:
#- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
- mvn clean install sonar:sonar